OutageAPI/OutageAPI/Models/Outage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace OutageAPI.Models
{
    public class Outage
    {
        [Key]
        public int ID { get; set; }
        public string Area { get; set; }
        public string Provider { get; set; }
        public string LeadTime { get; set; }
    }
    public class OutageDBContext : DbContext
    { 
        public DbSet<Outage> outages { get; set; }
    }

}

OutageAPI/OutageAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OutageAPI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OutageAPI/OutageAPI/Controllers/OutageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OutageAPI.Controllers
{
    public class OutageController : Controller
    {
        // GET: Outage
        public string Index()
        {
            return "This is my <b>default</b> action...";
        }
        // GET: Outage/Edit
        public ActionResult Edit()
        {
            return View();
        }
    }
}

OutageAPI/OutageAPI/Controllers/OutagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OutageAPI.Models;
using System.Text.Json;
using System.Threading.Tasks;
using PublicHoliday;

namespace OutageAPI.Controllers
{
    public class OutagesController : Controller
    {
        // public List<string> areas = new List<string>();
        public OutageDBContext db = new OutageDBContext();

        // GET: Outages
        public ActionResult Index()
        {
            return View(db.outages.ToList());
        }

        // GET: Outages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outage outage = db.outages.Find(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            return View(outage);
        }

        // GET: Outages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Outages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Area,Provider,LeadTime")] Outage outage)
        {
            if (ModelState.IsValid)
            {
                db.outages.Add(outage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(outage);
        }

        // GET: Outages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outage outage = db.outages.Find(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            return View(outage);
        }

        // POST: Outages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Area,Provider,LeadTime")] Outage outage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(outage);
        }

        // GET: Outages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Outage outage = db.outages.Find(id);
            if (outage == null)
            {
                return HttpNotFound();
            }
            return View(outage);
        }

        // POST: Outages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken] 
        public ActionResult DeleteConfirmed(int id)
        {
            Outage outage = db.outages.Find(id);
            db.outages.Remove(outage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult Json()
        {
            var outages = from m in db.outages
                          select m.Area;
            return Json(outages.ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult JsonProviders()
        {
            var outages = from m in db.outages
                          select m.Provider;
            return Json(outages.ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult JsonLeads()
        {
            var outages = from m in db.outages
                          select m.LeadTime;
            return Json(outages.ToList(), JsonRequestBehavior.AllowGet);
        }

        DateTime getBusinessDays(DateTime startdate, int days)
        {
            var date = startdate;
            while(days > 0)
            {
                date = date.AddDays(1);
                if(date.DayOfWeek == DayOfWeek.Saturday)
                {
                    date = date.AddDays(2);
                }
                if(date.DayOfWeek == DayOfWeek.Sunday)
                {
                    date = date.AddDays(1);
                }
                bool isholiday = new SouthAfricaPublicHoliday().IsPublicHoliday(date);
                if (isholiday)
                {
                    date = date.AddDays(1);
                }
                days--;
            }
            return date;
        }

        public JsonResult GetBDays()
        {
            var now = DateTime.Now;
            now = getBusinessDays(DateTime.Now, 21);
            return Json($"{now.Year}/{now.Month}/{now.Day}", JsonRequestBehavior.AllowGet);
        }
    }
}

OutageAPI/OutageAPI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OutageAPI/OutageAPI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OutageAPI/OutageAPI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

OutageAPI/OutageAPI/Views/Outage/OutageView.cshtml
@{
    ViewBag.Title = "OutageView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OutageView</h2>

OutageAPI/OutageAPI/Views/Outages/Create.cshtml
@model OutageAPI.Models.Outage

@{
    ViewBag.Title = "Add Outage";
}

<h2></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Log Outage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Provider, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provider, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provider, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LeadTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeadTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeadTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OutageAPI/OutageAPI/Views/Outages/Delete.cshtml
@model OutageAPI.Models.Outage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Outage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provider)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeadTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeadTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OutageAPI/OutageAPI/Views/Outages/Details.cshtml
@model OutageAPI.Models.Outage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Outage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provider)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeadTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeadTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OutageAPI/OutageAPI/Views/Outages/Edit.cshtml
@model OutageAPI.Models.Outage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Outage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Provider, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provider, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeadTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeadTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeadTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OutageAPI/OutageAPI/Views/Outages/Index.cshtml
@model IEnumerable<OutageAPI.Models.Outage>
@{
    ViewBag.Title = "Outage API Portal";
}

@using System.Text.Json;

<h2>Current Outages</h2>

<p>
    @Html.ActionLink("Add Outage", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Provider)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LeadTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provider)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeadTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
     }
</table>

<p><b><br />Development Tools :: Outage API</b></p>

<p>@Html.ActionLink("Render Json - Areas", "Json")</p>
<p>@Html.ActionLink("Render Json - Providers", "JsonProviders")</p>
<p>@Html.ActionLink("Render Json - LeadTimes", "JsonLeads")</p>

<p><b><br />Development Tools :: Acumatica</b></p>
<p>@Html.ActionLink("Business Days Calculation (21 business days from today, including weekends and holidays)", "GetBDays")</p>

OutageAPI/OutageAPI/Views/Outages/Json.cshtml
@model IEnumerable<OutageAPI.Models.Outage>

@{
    Layout = null;

}

@using System.Text.Json;
@using OutageAPI.Models; 
@{ 
    TempData.Keep("areastr");
    JsonDocument jsonify = JsonDocument.Parse(JsonSerializer.Serialize(TempData["areastr"]));
}

<html>
    <body>
        <object>@jsonify</object>
    </body>
</html>

OutageAPI/OutageAPI/Views/Outages/JsonLeads.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>JsonLeads</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

OutageAPI/OutageAPI/Views/Outages/JsonProviders.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>JsonArea</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

OutageAPI/OutageAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fibrestream Outage Portal", "Index", "Outages", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log an Area", "Index", "Outages")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fibrestream PTY Ltd</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>